// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gadumitrachioaiei/testswagger/models"
)

// TestrawjsonReader is a Reader for the Testrawjson structure.
type TestrawjsonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TestrawjsonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTestrawjsonOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTestrawjsonDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTestrawjsonOK creates a TestrawjsonOK with default headers values
func NewTestrawjsonOK() *TestrawjsonOK {
	return &TestrawjsonOK{}
}

/* TestrawjsonOK describes a response with status code 200, with default header values.

Success
*/
type TestrawjsonOK struct {
	Payload *models.SomeObject
}

func (o *TestrawjsonOK) Error() string {
	return fmt.Sprintf("[GET /rawjson][%d] testrawjsonOK  %+v", 200, o.Payload)
}
func (o *TestrawjsonOK) GetPayload() *models.SomeObject {
	return o.Payload
}

func (o *TestrawjsonOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SomeObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTestrawjsonDefault creates a TestrawjsonDefault with default headers values
func NewTestrawjsonDefault(code int) *TestrawjsonDefault {
	return &TestrawjsonDefault{
		_statusCode: code,
	}
}

/* TestrawjsonDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type TestrawjsonDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the testrawjson default response
func (o *TestrawjsonDefault) Code() int {
	return o._statusCode
}

func (o *TestrawjsonDefault) Error() string {
	return fmt.Sprintf("[GET /rawjson][%d] testrawjson default  %+v", o._statusCode, o.Payload)
}
func (o *TestrawjsonDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *TestrawjsonDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
