// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTestrawjsonParams creates a new TestrawjsonParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTestrawjsonParams() *TestrawjsonParams {
	return &TestrawjsonParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTestrawjsonParamsWithTimeout creates a new TestrawjsonParams object
// with the ability to set a timeout on a request.
func NewTestrawjsonParamsWithTimeout(timeout time.Duration) *TestrawjsonParams {
	return &TestrawjsonParams{
		timeout: timeout,
	}
}

// NewTestrawjsonParamsWithContext creates a new TestrawjsonParams object
// with the ability to set a context for a request.
func NewTestrawjsonParamsWithContext(ctx context.Context) *TestrawjsonParams {
	return &TestrawjsonParams{
		Context: ctx,
	}
}

// NewTestrawjsonParamsWithHTTPClient creates a new TestrawjsonParams object
// with the ability to set a custom HTTPClient for a request.
func NewTestrawjsonParamsWithHTTPClient(client *http.Client) *TestrawjsonParams {
	return &TestrawjsonParams{
		HTTPClient: client,
	}
}

/* TestrawjsonParams contains all the parameters to send to the API endpoint
   for the testrawjson operation.

   Typically these are written to a http.Request.
*/
type TestrawjsonParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the testrawjson params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TestrawjsonParams) WithDefaults() *TestrawjsonParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the testrawjson params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TestrawjsonParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the testrawjson params
func (o *TestrawjsonParams) WithTimeout(timeout time.Duration) *TestrawjsonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the testrawjson params
func (o *TestrawjsonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the testrawjson params
func (o *TestrawjsonParams) WithContext(ctx context.Context) *TestrawjsonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the testrawjson params
func (o *TestrawjsonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the testrawjson params
func (o *TestrawjsonParams) WithHTTPClient(client *http.Client) *TestrawjsonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the testrawjson params
func (o *TestrawjsonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TestrawjsonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
