swagger: '2.0'
info:
  version: 0.0.2
  title: Perceptor Decisions API
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    get:
      summary: Get the health status
      tags:
        - Health
      operationId: getHealth
      consumes:
        - application/json
      responses:
        '204':
          description: Success.
        '400':
          description: Validation error.
  /rawjson:
    get:
      summary: An endpoint that returns json data but the generated client does not deserialize
      tags:
        - test
      operationId: testrawjson
      consumes:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: "#/definitions/SomeObject"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - code
          - correlationId
        properties:
          code:
            type: integer
            format: int32
            x-nullable: false
          message:
            type: string
  SomeObject:
    type: object
    properties:
      kind:
        type: object
        properties:
          data:
            type: string
      data:
       type: object
