// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Perceptor Decisions API",
    "version": "0.0.2"
  },
  "basePath": "/api",
  "paths": {
    "/health": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Health"
        ],
        "summary": "Get the health status",
        "operationId": "getHealth",
        "responses": {
          "204": {
            "description": "Success."
          },
          "400": {
            "description": "Validation error."
          }
        }
      }
    },
    "/rawjson": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "test"
        ],
        "summary": "An endpoint that returns json data but the generated client does not deserialize",
        "operationId": "testrawjson",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SomeObject"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "data"
      ],
      "properties": {
        "data": {
          "type": "object",
          "required": [
            "code",
            "correlationId"
          ],
          "properties": {
            "code": {
              "type": "integer",
              "format": "int32",
              "x-nullable": false
            },
            "message": {
              "type": "string"
            }
          }
        }
      }
    },
    "SomeObject": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object"
        },
        "kind": {
          "type": "object",
          "properties": {
            "data": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Perceptor Decisions API",
    "version": "0.0.2"
  },
  "basePath": "/api",
  "paths": {
    "/health": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Health"
        ],
        "summary": "Get the health status",
        "operationId": "getHealth",
        "responses": {
          "204": {
            "description": "Success."
          },
          "400": {
            "description": "Validation error."
          }
        }
      }
    },
    "/rawjson": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "test"
        ],
        "summary": "An endpoint that returns json data but the generated client does not deserialize",
        "operationId": "testrawjson",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SomeObject"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "data"
      ],
      "properties": {
        "data": {
          "type": "object",
          "required": [
            "code",
            "correlationId"
          ],
          "properties": {
            "code": {
              "type": "integer",
              "format": "int32",
              "x-nullable": false
            },
            "message": {
              "type": "string"
            }
          }
        }
      }
    },
    "ErrorData": {
      "type": "object",
      "required": [
        "code",
        "correlationId"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "x-nullable": false
        },
        "message": {
          "type": "string"
        }
      }
    },
    "SomeObject": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object"
        },
        "kind": {
          "type": "object",
          "properties": {
            "data": {
              "type": "string"
            }
          }
        }
      }
    },
    "SomeObjectKind": {
      "type": "object",
      "properties": {
        "data": {
          "type": "string"
        }
      }
    }
  }
}`))
}
