// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthNoContentCode is the HTTP code returned for type GetHealthNoContent
const GetHealthNoContentCode int = 204

/*GetHealthNoContent Success.

swagger:response getHealthNoContent
*/
type GetHealthNoContent struct {
}

// NewGetHealthNoContent creates GetHealthNoContent with default headers values
func NewGetHealthNoContent() *GetHealthNoContent {

	return &GetHealthNoContent{}
}

// WriteResponse to the client
func (o *GetHealthNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetHealthBadRequestCode is the HTTP code returned for type GetHealthBadRequest
const GetHealthBadRequestCode int = 400

/*GetHealthBadRequest Validation error.

swagger:response getHealthBadRequest
*/
type GetHealthBadRequest struct {
}

// NewGetHealthBadRequest creates GetHealthBadRequest with default headers values
func NewGetHealthBadRequest() *GetHealthBadRequest {

	return &GetHealthBadRequest{}
}

// WriteResponse to the client
func (o *GetHealthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
